## 🌟 Exercise 1 : Array Creation and Manipulation

In [125]:
import numpy as np

arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 🌟 Exercise 2 : Type Conversion and Array Operations

In [126]:
alist =  [3.14, 2.17, 0, 1, 2]
arr = np.array(alist).astype(int)
arr

array([3, 2, 0, 1, 2])

## 🌟 Exercise 3 : Working with Multi-Dimensional Arrays

In [127]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

In [128]:
arr = np.random.rand(4,5)
arr

array([[0.53871791, 0.94547206, 0.08228145, 0.01739306, 0.87754177],
       [0.31991299, 0.06303485, 0.25024441, 0.9264608 , 0.73106032],
       [0.88340702, 0.29898479, 0.03398148, 0.1852771 , 0.61498717],
       [0.66792271, 0.88850872, 0.08055816, 0.37963854, 0.67154237]])

## 🌟 Exercise 5 : Indexing Arrays

In [129]:
arr = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
arr[1]

array([20, 21, 22, 23, 24])

## 🌟 Exercise 6 : Reversing elements

In [130]:
arr = np.arange(0, 10)
arr = np.flip(arr)
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 🌟 Exercise 7 : Identity Matrix

In [131]:
matrix = np.eye(4)
matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 🌟 Exercise 8 : Simple Aggregate Funcs

In [132]:
arr = np.arange(0,10)
sum = arr.sum()
avg = arr.mean()
print(f"Sum: {sum}, Average: {avg}")

Sum: 45, Average: 4.5


## 🌟 Exercise 9 : Create Array and Change its Structure

In [133]:
arr = np.arange(0,20)
arr = arr.reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 🌟 Exercise 10 : Conditional Selection of Values

In [ ]:
arr = np.arange(0,10)
arr = np.where(arr%2!=0)[0]
arr

array([1, 3, 5, 7, 9])

: 